"""Luna Pack tables

Revision ID: 2e3f9a1c4b5d
Revises: 4f0b50971d8d
Create Date: 2025-11-11 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e3f9a1c4b5d'
down_revision = '4f0b50971d8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Table lunar_reports
    op.create_table('lunar_reports',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('month', sa.String(), nullable=False),
        sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lunar_reports_id'), 'lunar_reports', ['id'], unique=False)
    op.create_index(op.f('ix_lunar_reports_month'), 'lunar_reports', ['month'], unique=False)
    op.create_index('ix_lunar_reports_user_month', 'lunar_reports', ['user_id', 'month'], unique=False)
    
    # Table lunar_voc_windows
    op.create_table('lunar_voc_windows',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('source', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lunar_voc_windows_id'), 'lunar_voc_windows', ['id'], unique=False)
    op.create_index(op.f('ix_lunar_voc_windows_start_at'), 'lunar_voc_windows', ['start_at'], unique=False)
    op.create_index(op.f('ix_lunar_voc_windows_end_at'), 'lunar_voc_windows', ['end_at'], unique=False)
    op.create_index('ix_lunar_voc_windows_range', 'lunar_voc_windows', ['start_at', 'end_at'], unique=False)
    
    # Table lunar_mansions_daily
    op.create_table('lunar_mansions_daily',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('mansion_id', sa.Integer(), nullable=False),
        sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('date')
    )
    op.create_index(op.f('ix_lunar_mansions_daily_id'), 'lunar_mansions_daily', ['id'], unique=False)
    op.create_index(op.f('ix_lunar_mansions_daily_date'), 'lunar_mansions_daily', ['date'], unique=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lunar_mansions_daily_date'), table_name='lunar_mansions_daily')
    op.drop_index(op.f('ix_lunar_mansions_daily_id'), table_name='lunar_mansions_daily')
    op.drop_table('lunar_mansions_daily')
    
    op.drop_index('ix_lunar_voc_windows_range', table_name='lunar_voc_windows')
    op.drop_index(op.f('ix_lunar_voc_windows_end_at'), table_name='lunar_voc_windows')
    op.drop_index(op.f('ix_lunar_voc_windows_start_at'), table_name='lunar_voc_windows')
    op.drop_index(op.f('ix_lunar_voc_windows_id'), table_name='lunar_voc_windows')
    op.drop_table('lunar_voc_windows')
    
    op.drop_index('ix_lunar_reports_user_month', table_name='lunar_reports')
    op.drop_index(op.f('ix_lunar_reports_month'), table_name='lunar_reports')
    op.drop_index(op.f('ix_lunar_reports_id'), table_name='lunar_reports')
    op.drop_table('lunar_reports')
    # ### end Alembic commands ###

