"""Initial migration

Revision ID: 4f0b50971d8d
Revises: 
Create Date: 2025-11-11 13:03:18.810832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f0b50971d8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('birth_time', sa.String(), nullable=True),
    sa.Column('birth_latitude', sa.String(), nullable=True),
    sa.Column('birth_longitude', sa.String(), nullable=True),
    sa.Column('birth_place_name', sa.String(), nullable=True),
    sa.Column('birth_timezone', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('lunar_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('return_date', sa.String(), nullable=True),
    sa.Column('lunar_ascendant', sa.String(), nullable=True),
    sa.Column('moon_house', sa.Integer(), nullable=True),
    sa.Column('moon_sign', sa.String(), nullable=True),
    sa.Column('aspects', sa.JSON(), nullable=True),
    sa.Column('planets', sa.JSON(), nullable=True),
    sa.Column('houses', sa.JSON(), nullable=True),
    sa.Column('interpretation', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lunar_returns_id'), 'lunar_returns', ['id'], unique=False)
    op.create_index(op.f('ix_lunar_returns_month'), 'lunar_returns', ['month'], unique=False)
    op.create_table('natal_charts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sun_sign', sa.String(), nullable=True),
    sa.Column('moon_sign', sa.String(), nullable=True),
    sa.Column('ascendant', sa.String(), nullable=True),
    sa.Column('planets', sa.JSON(), nullable=True),
    sa.Column('houses', sa.JSON(), nullable=True),
    sa.Column('aspects', sa.JSON(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_natal_charts_id'), 'natal_charts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_natal_charts_id'), table_name='natal_charts')
    op.drop_table('natal_charts')
    op.drop_index(op.f('ix_lunar_returns_month'), table_name='lunar_returns')
    op.drop_index(op.f('ix_lunar_returns_id'), table_name='lunar_returns')
    op.drop_table('lunar_returns')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

